[general]
host = "0.0.0.0"
port = 443
root = "/var/marvins-frequency/marvins-frequency"

log-level = "error"

page404 = "./404.html"

http2 = true
http2-tls-cert = "/etc/letsencrypt/live/marvins-frequency.com/fullchain.pem"
http2-tls-key = "/etc/letsencrypt/live/marvins-frequency.com/privkey.pem"
